# Generated by Django 5.2.2 on 2025-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodleApp', '0002_remove_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, help_text='URL to redirect when user clicks Buy', max_length=500, null=True),
        ),
    ]
