# Generated by Django 5.2.2 on 2025-06-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodleApp', '0004_portfoliocategory_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content_snippet', models.TextField()),
                ('body', models.TextField()),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
