# Generated by Django 5.2.2 on 2025-06-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doodleApp', '0006_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='project',
        ),
    ]
